import { PlatformConfig, PlatformSlug, FAQItem, BlogPost, AdPlacementConfig, SiteSettings } from '../types';

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  siteName: 'OmniFetch Pro',
  shortName: 'OmniFetch',
  tagline: 'أفضل وأسرع أداة مجانية لتحميل الفيديوهات والريلز بدون علامة مائية وبدقة HD عالية',
  logoUrl: '',
  faviconUrl: '',
  contactEmail: 'support@omnifetchpro.com',
  primaryColor: '#9333ea',
  secondaryColor: '#3b82f6',
  fontFamily: 'Plus Jakarta Sans',
  headerStyle: 'sticky',
  headerBlur: 'heavy',
  buttonRadius: 'rounded-xl',
  cardStyle: 'glass',
  logoHeightPx: 40,
  platformIconsCustom: {},
  platformColorsCustom: {},
  adsenseClientId: 'ca-pub-1234567890000000',
  ga4Id: 'G-OMNIDOWNLOADER2026',
  gtmId: 'GTM-OMNIDOWNLOADER',
  clarityId: 'clarity_omnidownloader',
  fbPixelId: '123456789012345',
  maintenanceMode: false,
  rateLimitPerMinute: 30,
  allowMp3Conversion: true,
  watermarkFreeByDefault: true,
};

export const PLATFORMS_CONFIG: Record<PlatformSlug, PlatformConfig> = {
  all: {
    slug: 'all',
    name: 'All Platforms',
    iconName: 'Globe',
    color: 'from-blue-600 to-indigo-600',
    badgeBg: 'bg-indigo-500/10 border-indigo-500/30',
    badgeText: 'text-indigo-400',
    placeholderUrl: 'https://www.tiktok.com/@user/video/123456789',
    popular: true,
    seoKeywords: ['video downloader', 'free online video downloader', 'mp4 downloader', 'mp3 converter', 'no watermark downloader'],
    supportedFormats: ['4K MP4', '1080p HD', '720p', 'Audio MP3'],
    titleTemplate: {
      ar: 'أداة تحميل الفيديوهات الشاملة لجميع المنصات',
      en: 'Universal Online Video Downloader for All Platforms',
      fr: 'Téléchargeur de vidéos universel pour toutes les plateformes',
      es: 'Descargador de videos universal para todas las plataformas',
      de: 'Universeller Video-Downloader für alle Plattformen',
      it: 'Downloader video universale per tutte le piattaforme',
    },
    subtitle: {
      ar: 'قم بتحميل الفيديوهات والريلز من تيك توك، يوتيوب، فيسبوك، إنستغرام وسناب شات بسرعة فائقة وبدون علامة مائية.',
      en: 'Download videos and reels from TikTok, YouTube, Facebook, Instagram and Snapchat in HD with no watermark.',
      fr: 'Téléchargez des vidéos et des reels depuis TikTok, YouTube, Facebook, Instagram et Snapchat en HD sans filigrane.',
      es: 'Descarga videos y reels de TikTok, YouTube, Facebook, Instagram y Snapchat en HD sin marca de agua.',
      de: 'Laden Sie Videos und Reels von TikTok, YouTube, Facebook, Instagram und Snapchat in HD ohne Wasserzeichen herunter.',
      it: 'Scarica video e reel da TikTok, YouTube, Facebook, Instagram e Snapchat in HD senza filigrana.',
    },
    description: {
      ar: 'خدمة المجانية الأولى لتحميل الفيديوهات بجودة عالية وبدون إعلانات مزعجة.',
      en: 'The #1 free service to download online videos in full HD with zero popups.',
      fr: 'Le service gratuit n°1 pour télécharger des vidéos en Full HD sans fenêtres intempestives.',
      es: 'El servicio gratuito n.º 1 para descargar videos en Full HD sin ventanas emergentes.',
      de: 'Der kostenlose Dienst Nr. 1 zum Herunterladen von Videos in Full HD ohne Popups.',
      it: 'Il servizio gratuito n. 1 per scaricare video in Full HD senza popup.',
    },
    features: {
      ar: ['بدون علامة مائية', 'تحميل فائق السرعة', 'مجاني 100%', 'دعم الجودة العالية 4K/1080p', 'تحويل الصوت إلى MP3'],
      en: ['No Watermark', 'Ultra Fast Engine', '100% Free Forever', 'Supports 4K/1080p HD', 'Extract MP3 Audio'],
      fr: ['Sans filigrane', 'Moteur ultra rapide', '100% Gratuit', 'Supporte 4K/1080p HD', 'Extraction MP3'],
      es: ['Sin marca de agua', 'Motor ultrarrápido', '100% Gratis', 'Soporta 4K/1080p HD', 'Extracción MP3'],
      de: ['Ohne Wasserzeichen', 'Schnelle Engine', '100% Kostenlos', 'Unterstützt 4K/1080p HD', 'MP3 Extraktion'],
      it: ['Senza filigrana', 'Engine veloce', '100% Gratuito', 'Supporta 4K/1080p HD', 'Estrazione MP3'],
    },
  },
  tiktok: {
    slug: 'tiktok',
    name: 'TikTok',
    iconName: 'Video',
    color: 'from-pink-500 via-rose-500 to-red-500',
    badgeBg: 'bg-pink-500/10 border-pink-500/30',
    badgeText: 'text-pink-400',
    placeholderUrl: 'https://www.tiktok.com/@creator/video/7123456789',
    popular: true,
    seoKeywords: ['tiktok downloader', 'tiktok video download no watermark', 'ssstik', 'snaptik', 'download tiktok mp3'],
    supportedFormats: ['MP4 No Watermark HD', 'MP4 Original', 'Audio MP3'],
    titleTemplate: {
      ar: 'أداة تحميل فيديوهات تيك توك بدون علامة مائية (TikTok Downloader)',
      en: 'TikTok Video Downloader Without Watermark (HD MP4 & MP3)',
      fr: 'Téléchargeur de Vidéos TikTok Sans Filigrane (HD MP4 & MP3)',
      es: 'Descargador de Videos de TikTok Sin Marca de Agua (HD MP4 y MP3)',
      de: 'TikTok Video Downloader Ohne Wasserzeichen (HD MP4 & MP3)',
      it: 'Downloader Video TikTok Senza Filigrana (HD MP4 e MP3)',
    },
    subtitle: {
      ar: 'احفظ أي فيديو من تيك توك بأعلى جودة جودة ممكنة وبدون الشعار الزلق فورًا.',
      en: 'Save any TikTok video in crisp HD with the watermark completely removed instantly.',
      fr: 'Sauvegardez n\'importe quelle vidéo TikTok en HD avec suppression du filigrane.',
      es: 'Guarda cualquier video de TikTok en HD eliminando la marca de agua al instante.',
      de: 'Speichern Sie jedes TikTok-Video in HD ohne Wasserzeichen sofort.',
      it: 'Salva qualsiasi video TikTok in HD senza filigrana all\'istante.',
    },
    description: {
      ar: 'أداة تيك توك التلقائية لإزالة العلامة المائية وتنزيل المقاطع الصوتية الأصلية.',
      en: 'Automatic TikTok watermark removal tool & audio extractor.',
      fr: 'Outil de suppression automatique du filigrane TikTok et d\'extraction audio.',
      es: 'Herramienta de eliminación de marca de agua de TikTok y extractor de audio.',
      de: 'Automatische Entfernung des TikTok-Wasserzeichens und Audio-Extraktor.',
      it: 'Strumento di rimozione della filigrana TikTok ed estrattore audio.',
    },
    features: {
      ar: ['إزالة الشعار تلقائيًا', 'تحميل بصيغة MP3 للموسيقى', 'دعم الحسابات الشخصية والخدمات', 'متوافق مع الأندرويد والآيفون'],
      en: ['Automatic Watermark Removal', 'Extract Original Background MP3', 'Compatible with iOS & Android', 'Unlimited Saves'],
      fr: ['Suppression automatique du logo', 'Extraire le son original MP3', 'Compatible iOS et Android', 'Sauvegardes illimitées'],
      es: ['Eliminación automática de marca', 'Extraer MP3 de fondo original', 'Compatible con iOS y Android', 'Guardado ilimitado'],
      de: ['Automatische Logorentfernung', 'Original MP3 extrahieren', 'Kompatibel mit iOS & Android', 'Unbegrenzt'],
      it: ['Rimozione automatica del logo', 'Estrai MP3 originale', 'Compatibile con iOS e Android', 'Download illimitati'],
    },
  },
  facebook: {
    slug: 'facebook',
    name: 'Facebook',
    iconName: 'Facebook',
    color: 'from-blue-600 to-blue-700',
    badgeBg: 'bg-blue-500/10 border-blue-500/30',
    badgeText: 'text-blue-400',
    placeholderUrl: 'https://www.facebook.com/watch/?v=1015123456789',
    popular: true,
    seoKeywords: ['facebook video downloader', 'fb video download hd', 'fdown', 'download facebook video 1080p'],
    supportedFormats: ['MP4 1080p Full HD', 'MP4 720p HD', 'MP4 SD', 'MP3 Audio'],
    titleTemplate: {
      ar: 'برنامج تحميل فيديوهات فيسبوك بجودة عالية 1080p HD',
      en: 'Facebook Video Downloader 1080p Full HD & MP3',
      fr: 'Téléchargeur de Vidéos Facebook 1080p Full HD',
      es: 'Descargador de Videos de Facebook 1080p Full HD',
      de: 'Facebook Video Downloader 1080p Full HD',
      it: 'Downloader Video Facebook 1080p Full HD',
    },
    subtitle: {
      ar: 'تحميل مقاطع فيسبوك العامة والصفحات والمجموعات بجودة Full HD و 4K مباشرة.',
      en: 'Download public Facebook videos, page posts, and group media in 1080p Full HD.',
      fr: 'Téléchargez des vidéos publiques Facebook et des publications de pages en Full HD.',
      es: 'Descarga videos públicos de Facebook y publicaciones de páginas en Full HD.',
      de: 'Laden Sie öffentliche Facebook-Videos und Seitenbeiträge in Full HD herunter.',
      it: 'Scarica video pubblici di Facebook e post di pagine in Full HD.',
    },
    description: {
      ar: 'أسرع طريقة لتحميل فيديوهات الفيسبوك بأعلى دقة ووضوح.',
      en: 'The fastest way to download Facebook videos in highest available quality.',
      fr: 'Le moyen le plus rapide de télécharger des vidéos Facebook en haute qualité.',
      es: 'La forma más rápida de descargar videos de Facebook en la máxima calidad.',
      de: 'Der schnellste Weg, Facebook-Videos in höchster Qualität herunterzuladen.',
      it: 'Il modo più veloce per scaricare video da Facebook alla massima qualità.',
    },
    features: {
      ar: ['دعم جودة 1080p Full HD', 'سرعة تنزيل فائقة', 'تحويل المقطع إلى MP3', 'بدون تثبيت برامج'],
      en: ['Full HD 1080p & 4K Quality', 'Blazing Fast Speeds', 'MP3 Audio Extraction', 'No Software Required'],
      fr: ['Qualité Full HD 1080p', 'Vitesse ultra rapide', 'Extraction MP3', 'Aucun logiciel requis'],
      es: ['Calidad Full HD 1080p', 'Velocidad ultrarrápida', 'Extracción de MP3', 'Sin programas'],
      de: ['Full HD 1080p Qualität', 'Blitzschnelle Downloads', 'MP3 Extraktion', 'Keine Software nötig'],
      it: ['Qualità Full HD 1080p', 'Velocità elevatissima', 'Estrazione MP3', 'Nessun software'],
    },
  },
  'facebook-reels': {
    slug: 'facebook-reels',
    name: 'Facebook Reels',
    iconName: 'Clapperboard',
    color: 'from-blue-500 via-indigo-600 to-purple-600',
    badgeBg: 'bg-indigo-500/10 border-indigo-500/30',
    badgeText: 'text-indigo-400',
    placeholderUrl: 'https://www.facebook.com/reel/123456789012345',
    popular: true,
    seoKeywords: ['facebook reels downloader', 'fb reel download hd', 'download facebook reels online'],
    supportedFormats: ['MP4 HD Reels', 'MP3 Audio'],
    titleTemplate: {
      ar: 'تحميل ريلز فيسبوك (Facebook Reels Downloader HD)',
      en: 'Facebook Reels Downloader in HD Quality',
      fr: 'Téléchargeur de Facebook Reels en HD',
      es: 'Descargador de Reels de Facebook en HD',
      de: 'Facebook Reels Downloader in HD-Qualität',
      it: 'Downloader per Reel di Facebook in HD',
    },
    subtitle: {
      ar: 'حمل مقاطع ريلز الفيسبوك القصيرة بجودة ممتازة وصوت نقي بدقائق.',
      en: 'Download short Facebook reels in crystal clear HD quality instantly.',
      fr: 'Téléchargez des reels courts Facebook en qualité HD très nette.',
      es: 'Descarga reels cortos de Facebook en calidad HD con sonido nítido.',
      de: 'Laden Sie kurze Facebook-Reels in gestochen scharfer HD-Qualität herunter.',
      it: 'Scarica i reel brevi di Facebook in qualità HD nitida.',
    },
    description: {
      ar: 'أداة سريعة ومجانية مخصصة لتنزيل مقاطع ريلز فيسبوك.',
      en: 'Dedicated fast tool for saving Facebook reels.',
      fr: 'Outil rapide dédié au téléchargement des reels Facebook.',
      es: 'Herramienta rápida para guardar reels de Facebook.',
      de: 'Spezielle schnelle Engine zum Speichern von Facebook-Reels.',
      it: 'Strumento rapido dedicato al salvataggio dei reel di Facebook.',
    },
    features: {
      ar: ['تنزيل بنقرة واحدة', 'دعم الصوت MP3', 'جودة Reels عالية', 'مجاني لجميع الأجهزة'],
      en: ['One-Click Downloads', 'Audio MP3 Support', 'High-bitrate Video', 'Free on All Devices'],
      fr: ['Téléchargement en 1 clic', 'Support Audio MP3', 'Haute qualité vidéo', 'Gratuit sur tous les appareils'],
      es: ['Descarga en 1 clic', 'Soporte de audio MP3', 'Video de alta calidad', 'Gratis en todo dispositivo'],
      de: ['Download mit 1 Klick', 'MP3 Audio Support', 'Hohe Bitrate', 'Kostenlos auf allen Geräten'],
      it: ['Download con 1 clic', 'Supporto audio MP3', 'Video ad alta qualità', 'Gratuito su tutti i dispositivi'],
    },
  },
  instagram: {
    slug: 'instagram',
    name: 'Instagram',
    iconName: 'Instagram',
    color: 'from-amber-500 via-rose-500 to-purple-600',
    badgeBg: 'bg-rose-500/10 border-rose-500/30',
    badgeText: 'text-rose-400',
    placeholderUrl: 'https://www.instagram.com/p/C1234567890/',
    popular: true,
    seoKeywords: ['instagram video downloader', 'igram', 'savefrom instagram', 'download instagram posts', 'insta mp4'],
    supportedFormats: ['MP4 Full HD', 'JPEG Image', 'MP3 Audio'],
    titleTemplate: {
      ar: 'برنامج تحميل فيديوهات إنستغرام بجودة عالية (Instagram Downloader)',
      en: 'Instagram Video & Post Downloader (Full HD MP4)',
      fr: 'Téléchargeur de Vidéos et Posts Instagram (Full HD MP4)',
      es: 'Descargador de Videos y Publicaciones de Instagram (Full HD MP4)',
      de: 'Instagram Video & Post Downloader (Full HD MP4)',
      it: 'Downloader Video e Post Instagram (Full HD MP4)',
    },
    subtitle: {
      ar: 'قم بتحميل الفيديوهات والمنشورات والصور من إنستغرام بوضوح متناهي.',
      en: 'Download videos, carousels, and photos from Instagram in native resolution.',
      fr: 'Téléchargez des vidéos, carrousels et photos depuis Instagram en résolution native.',
      es: 'Descarga videos, carruseles y fotos de Instagram en resolución original.',
      de: 'Laden Sie Videos, Karussells und Fotos von Instagram in Originalauflösung herunter.',
      it: 'Scarica video, caroselli e foto da Instagram a risoluzione originale.',
    },
    description: {
      ar: 'احفظ محتوى إنستغرام المفضل في الاستوديو الخاص بك فورًا.',
      en: 'Save your favorite Instagram media directly to your gallery.',
      fr: 'Enregistrez vos médias Instagram préférés dans votre galerie.',
      es: 'Guarda tus contenidos favoritos de Instagram directamente en tu galería.',
      de: 'Speichern Sie Ihre Lieblingsmedien von Instagram in Ihrer Galerie.',
      it: 'Salva i tuoi media preferiti di Instagram nella tua galleria.',
    },
    features: {
      ar: ['دعم الفيديوهات والصور', 'دقة Full HD أصيلة', 'تحميل سريع جداً', 'خصوصية وأمان كامليين'],
      en: ['Videos & Carousel Photos', 'Native Full HD Quality', 'Blazing Transfer Speed', '100% Private & Anonymous'],
      fr: ['Vidéos et Carrousels', 'Qualité Full HD originale', 'Vitesse de transfert rapide', 'Privé et anonyme'],
      es: ['Videos y fotos carrusel', 'Calidad Full HD original', 'Velocidad de transferencia alta', 'Privado y anónimo'],
      de: ['Videos & Karussell-Fotos', 'Original Full HD Qualität', 'Schneller Transfer', 'Anonym und sicher'],
      it: ['Video e foto carosello', 'Qualità Full HD originale', 'Velocità di trasferimento', 'Anonimo e sicuro'],
    },
  },
  'instagram-reels': {
    slug: 'instagram-reels',
    name: 'Instagram Reels',
    iconName: 'Tv',
    color: 'from-purple-600 via-pink-600 to-amber-500',
    badgeBg: 'bg-purple-500/10 border-purple-500/30',
    badgeText: 'text-purple-400',
    placeholderUrl: 'https://www.instagram.com/reel/C1234567890/',
    popular: true,
    seoKeywords: ['instagram reels downloader', 'insta reel saver', 'download ig reels audio', 'save ig reel hd'],
    supportedFormats: ['MP4 HD Reels', 'Audio MP3'],
    titleTemplate: {
      ar: 'تحميل إنستغرام ريلز بدون برامج (Instagram Reels Downloader)',
      en: 'Instagram Reels Downloader in HD MP4',
      fr: 'Téléchargeur de Reels Instagram en HD MP4',
      es: 'Descargador de Reels de Instagram en HD MP4',
      de: 'Instagram Reels Downloader in HD MP4',
      it: 'Downloader di Reel Instagram in HD MP4',
    },
    subtitle: {
      ar: 'حمل فيديوهات ريلز انستقرام مع الصوت والتأثيرات كاملة بدون نقص.',
      en: 'Download IG reels with original sound, effects, and full quality.',
      fr: 'Téléchargez les reels IG avec le son d\'origine et la qualité maximale.',
      es: 'Descarga reels de IG con el sonido original y máxima calidad.',
      de: 'Laden Sie IG-Reels mit Originalton und bester Qualität herunter.',
      it: 'Scarica reel di IG con audio originale e massima qualità.',
    },
    description: {
      ar: 'أفضل أداة مجانية لحفظ ريلز إنستقرام بجودة 1080p.',
      en: 'Best free tool to save Instagram reels in 1080p resolution.',
      fr: 'Meilleur outil gratuit pour sauvegarder des reels Instagram en 1080p.',
      es: 'La mejor herramienta gratuita para guardar reels de Instagram en 1080p.',
      de: 'Beste kostenlose Engine zum Speichern von Instagram-Reels in 1080p.',
      it: 'Miglior strumento gratuito per salvare reel di Instagram in 1080p.',
    },
    features: {
      ar: ['حفظ الريلز مع الصوت', 'جودة عالية 1080p', 'تحويل إلى MP3', 'لا يلزم تسجيل الدخول'],
      en: ['Reels with Audio Included', '1080p Crisp Video', 'MP3 Audio Convert', 'No Login Required'],
      fr: ['Reels avec audio inclus', 'Vidéo nette 1080p', 'Conversion MP3', 'Connexion non requise'],
      es: ['Reels con audio incluido', 'Video nítido 1080p', 'Conversión a MP3', 'Sin iniciar sesión'],
      de: ['Reels mit Ton', '1080p Scharfes Video', 'MP3 Konvertierung', 'Kein Login nötig'],
      it: ['Reel con audio incluso', 'Video nitido 1080p', 'Convertitore MP3', 'Nessun login richiesto'],
    },
  },
  youtube: {
    slug: 'youtube',
    name: 'YouTube',
    iconName: 'Youtube',
    color: 'from-red-600 to-rose-700',
    badgeBg: 'bg-red-500/10 border-red-500/30',
    badgeText: 'text-red-400',
    placeholderUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    popular: true,
    seoKeywords: ['youtube video downloader', 'yt mp4', 'yt mp3', 'youtube 4k downloader', 'savefrom youtube'],
    supportedFormats: ['4K 2160p', '1080p Full HD', '720p HD', 'Audio MP3 320kbps'],
    titleTemplate: {
      ar: 'تحميل فيديوهات يوتيوب بجودة 4K و 1080p HD (YouTube Downloader)',
      en: 'YouTube Video & Audio Downloader (4K, 1080p & MP3)',
      fr: 'Téléchargeur de Vidéos YouTube (4K, 1080p & MP3)',
      es: 'Descargador de Videos de YouTube (4K, 1080p y MP3)',
      de: 'YouTube Video Downloader (4K, 1080p & MP3)',
      it: 'Downloader Video YouTube (4K, 1080p e MP3)',
    },
    subtitle: {
      ar: 'حمل أي فيديو من يوتيوب بأعلى جودة متوفرة أو قم بتحويله إلى MP3 صوتي.',
      en: 'Download YouTube videos in up to 4K resolution or convert directly to 320kbps MP3 audio.',
      fr: 'Téléchargez des vidéos YouTube jusqu\'en 4K ou convertissez directement en MP3 320kbps.',
      es: 'Descarga videos de YouTube en hasta 4K o convierte a audio MP3 de 320kbps.',
      de: 'Laden Sie YouTube-Videos in bis zu 4K herunter oder konvertieren Sie in MP3.',
      it: 'Scarica video da YouTube fino a 4K o convertili in audio MP3 a 320kbps.',
    },
    description: {
      ar: 'أداة معالجة فيديوهات يوتيوب بسرعة واستخلاص MP3 بدقة عالية.',
      en: 'High speed YouTube media processor & high-bitrate MP3 converter.',
      fr: 'Processeur média YouTube rapide et convertisseur MP3 haute qualité.',
      es: 'Procesador de medios de YouTube y convertidor MP3 de alta calidad.',
      de: 'Schneller YouTube-Medienprozessor und MP3-Konverter.',
      it: 'Elaboratore di media YouTube ad alta velocità e convertitore MP3.',
    },
    features: {
      ar: ['دعم جودة 4K و 1080p', 'تحويل الصوت 320kbps MP3', 'معالجة مباشرة', 'لا حدود للحجم'],
      en: ['4K & 1080p Quality Options', 'High Bitrate 320kbps MP3', 'Instant Processing', 'No File Size Limit'],
      fr: ['Options 4K et 1080p', 'MP3 320kbps haut débit', 'Traitement instantané', 'Pas de limite de taille'],
      es: ['Opciones 4K y 1080p', 'MP3 de 320kbps de alta calidad', 'Procesamiento instantáneo', 'Sin límite de tamaño'],
      de: ['4K & 1080p Optionen', '320kbps MP3 Audio', 'Sofortige Verarbeitung', 'Keine Größenbeschränkung'],
      it: ['Opzioni 4K e 1080p', 'MP3 a 320kbps', 'Elaborazione immediata', 'Nessun limite di dimensione'],
    },
  },
  'youtube-shorts': {
    slug: 'youtube-shorts',
    name: 'YouTube Shorts',
    iconName: 'PlaySquare',
    color: 'from-red-500 via-rose-600 to-orange-500',
    badgeBg: 'bg-rose-500/10 border-rose-500/30',
    badgeText: 'text-rose-400',
    placeholderUrl: 'https://www.youtube.com/shorts/1234567890',
    popular: true,
    seoKeywords: ['youtube shorts downloader', 'yt shorts mp4', 'download shorts video', 'youtube shorts to mp3'],
    supportedFormats: ['MP4 HD Shorts', 'MP3 Audio'],
    titleTemplate: {
      ar: 'برنامج تحميل شورتس يوتيوب (YouTube Shorts Downloader)',
      en: 'YouTube Shorts Downloader in HD MP4 & MP3',
      fr: 'Téléchargeur de YouTube Shorts en HD MP4 & MP3',
      es: 'Descargador de YouTube Shorts en HD MP4 y MP3',
      de: 'YouTube Shorts Downloader in HD MP4 & MP3',
      it: 'Downloader di YouTube Shorts in HD MP4 e MP3',
    },
    subtitle: {
      ar: 'احفظ فيديوهات شورتس القصيرة من يوتيوب بجودة ممتازة على جوالك فورًا.',
      en: 'Save vertical YouTube shorts videos directly to your phone or computer.',
      fr: 'Enregistrez des vidéos verticales YouTube Shorts directement sur votre appareil.',
      es: 'Guarda videos verticales de YouTube Shorts directamente en tu teléfono.',
      de: 'Speichern Sie vertikale YouTube Shorts direkt auf Ihrem Smartphone.',
      it: 'Salva i video verticali di YouTube Shorts direttamente sul tuo telefono.',
    },
    description: {
      ar: 'أسرع محرك لتنزيل مقاطع شورتس يوتيوب.',
      en: 'Fastest engine for downloading YouTube Shorts content.',
      fr: 'Moteur le plus rapide pour télécharger le contenu YouTube Shorts.',
      es: 'El motor más rápido para descargar contenido de YouTube Shorts.',
      de: 'Schnellste Engine zum Herunterladen von YouTube Shorts.',
      it: 'Il motore più veloce per scaricare i contenuti di YouTube Shorts.',
    },
    features: {
      ar: ['تنزيل بنقرة واحدة', 'دقة HD 1080p كاملة', 'استخراج MP3 الصوتي', 'مجاني لجميع الأجهزة'],
      en: ['1-Click Direct Download', 'Full HD 1080p Resolution', 'Audio MP3 Extraction', 'Free on Mobile & PC'],
      fr: ['Téléchargement en 1 clic', 'Résolution Full HD 1080p', 'Extraction audio MP3', 'Gratuit mobile et PC'],
      es: ['Descarga directa en 1 clic', 'Resolución Full HD 1080p', 'Extracción de audio MP3', 'Gratis en móvil y PC'],
      de: ['1-Klick-Direktdownload', 'Full HD 1080p Auflösung', 'MP3 Audio Extraktion', 'Kostenlos mobil & PC'],
      it: ['Download diretto in 1 clic', 'Risoluzione Full HD 1080p', 'Estrazione audio MP3', 'Gratuito per cellulari e PC'],
    },
  },
  snapchat: {
    slug: 'snapchat',
    name: 'Snapchat',
    iconName: 'Ghost',
    color: 'from-amber-400 to-yellow-500',
    badgeBg: 'bg-yellow-500/10 border-yellow-500/30',
    badgeText: 'text-yellow-400',
    placeholderUrl: 'https://story.snapchat.com/s/user/1234567890',
    popular: true,
    seoKeywords: ['snapchat video downloader', 'download snapchat spotlight', 'snapchat story saver'],
    supportedFormats: ['MP4 HD Video'],
    titleTemplate: {
      ar: 'تحميل فيديوهات سناب شات والستوري (Snapchat Downloader)',
      en: 'Snapchat Video & Spotlight Downloader (HD MP4)',
      fr: 'Téléchargeur de Vidéos Snapchat et Spotlight',
      es: 'Descargador de Videos y Spotlight de Snapchat',
      de: 'Snapchat Video & Spotlight Downloader',
      it: 'Downloader Video e Spotlight Snapchat',
    },
    subtitle: {
      ar: 'احفظ فيديوهات سبوتلايت وستوريات سناب شات العامة بوضوح عالي.',
      en: 'Save public Snapchat Spotlight videos and stories in crystal HD.',
      fr: 'Sauvegardez les vidéos publiques Snapchat Spotlight et stories en HD.',
      es: 'Guarda videos públicos de Snapchat Spotlight e historias en HD.',
      de: 'Speichern Sie öffentliche Snapchat Spotlight Videos und Stories in HD.',
      it: 'Salva video pubblici di Snapchat Spotlight e storie in HD.',
    },
    description: {
      ar: 'أداة تحميل سبوتلايت سناب شات في ثوانٍ.',
      en: 'Save Snapchat spotlight clips in seconds.',
      fr: 'Enregistrez des clips Snapchat Spotlight en quelques secondes.',
      es: 'Guarda clips de Snapchat Spotlight en segundos.',
      de: 'Speichern Sie Snapchat Spotlight Clips in Sekundenschnelle.',
      it: 'Salva clip di Snapchat Spotlight in pochi secondi.',
    },
    features: {
      ar: ['دعم مقاطع Spotlight', 'حفظ ستوريات سناب العادية', 'جودة فيديو واضحة', 'بدون تسجيل'],
      en: ['Spotlight Videos Supported', 'Public Stories Download', 'Crisp HD Resolution', 'No Login Needed'],
      fr: ['Vidéos Spotlight supportées', 'Téléchargement des stories', 'Résolution HD nette', 'Sans connexion'],
      es: ['Soporta videos Spotlight', 'Descarga historias públicas', 'Resolución HD nítida', 'Sin iniciar sesión'],
      de: ['Spotlight Videos unterstützt', 'Öffentliche Stories speichern', 'Scharfe HD Auflösung', 'Kein Login'],
      it: ['Supporta video Spotlight', 'Download storie pubbliche', 'Risoluzione HD nitida', 'Nessun login'],
    },
  },
  twitter: {
    slug: 'twitter',
    name: 'X (Twitter)',
    iconName: 'Twitter',
    color: 'from-sky-500 to-blue-600',
    badgeBg: 'bg-sky-500/10 border-sky-500/30',
    badgeText: 'text-sky-400',
    placeholderUrl: 'https://twitter.com/user/status/123456789012345',
    popular: false,
    seoKeywords: ['twitter video downloader', 'x video download', 'twitter mp4', 'download x video hd'],
    supportedFormats: ['MP4 1080p HD', 'MP4 720p', 'Audio MP3'],
    titleTemplate: {
      ar: 'تحميل فيديوهات تويتر / منصة X بجودة عالية (Twitter Video Downloader)',
      en: 'X / Twitter Video Downloader (HD MP4)',
      fr: 'Téléchargeur de Vidéos X / Twitter (HD MP4)',
      es: 'Descargador de Videos de X / Twitter (HD MP4)',
      de: 'X / Twitter Video Downloader (HD MP4)',
      it: 'Downloader Video X / Twitter (HD MP4)',
    },
    subtitle: {
      ar: 'قم بتنزيل الفيديوهات والصور المتحركة GIF من منشورات منصة تويتر/X مباشرة.',
      en: 'Download videos and GIFs embedded in X (Twitter) posts in high definition.',
      fr: 'Téléchargez des vidéos et des GIF intégrés aux publications X (Twitter) en haute définition.',
      es: 'Descarga videos y GIF de publicaciones de X (Twitter) en alta definición.',
      de: 'Laden Sie Videos und GIFs aus X (Twitter) Beiträgen in High Definition herunter.',
      it: 'Scarica video e GIF incorporati nei post di X (Twitter) in alta definizione.',
    },
    description: {
      ar: 'أداة سريعة لحفظ فيديوهات تويتر في أجهزة الكمبيوتر والموبايل.',
      en: 'Fast tool for saving X (Twitter) media.',
      fr: 'Outil rapide pour sauvegarder les médias X (Twitter).',
      es: 'Herramienta rápida para guardar contenidos de X (Twitter).',
      de: 'Schnelles Tool zum Speichern von X (Twitter) Medien.',
      it: 'Strumento rapido per salvare i media di X (Twitter).',
    },
    features: {
      ar: ['دعم جودة 1080p', 'تحميل الصور المتحركة GIF', 'سرعة استخراج عالية', 'بدون تسجيل حساب'],
      en: ['1080p HD Quality', 'Supports GIFs & MP4', 'Instant Extraction', 'No Account Required'],
      fr: ['Qualité HD 1080p', 'Supporte GIF et MP4', 'Extraction instantanée', 'Aucun compte requis'],
      es: ['Calidad HD 1080p', 'Soporta GIF y MP4', 'Extracción instantánea', 'Sin cuenta requerida'],
      de: ['1080p HD Qualität', 'Unterstützt GIFs & MP4', 'Sofortige Extraktion', 'Kostenlos ohne Konto'],
      it: ['Qualità HD 1080p', 'Supporta GIF e MP4', 'Estrazione immediata', 'Nessun account richiesto'],
    },
  },
  pinterest: {
    slug: 'pinterest',
    name: 'Pinterest',
    iconName: 'Pin',
    color: 'from-red-600 to-rose-600',
    badgeBg: 'bg-red-500/10 border-red-500/30',
    badgeText: 'text-red-400',
    placeholderUrl: 'https://pin.it/123456789',
    popular: false,
    seoKeywords: ['pinterest video downloader', 'download pinterest pin video', 'pin downloader'],
    supportedFormats: ['MP4 HD Video', 'JPEG Image'],
    titleTemplate: {
      ar: 'تحميل فيديوهات بينتريست (Pinterest Video Downloader)',
      en: 'Pinterest Video & Image Downloader',
      fr: 'Téléchargeur de Vidéos Pinterest',
      es: 'Descargador de Videos de Pinterest',
      de: 'Pinterest Video Downloader',
      it: 'Downloader Video Pinterest',
    },
    subtitle: {
      ar: 'احفظ دبابيس الفيديوهات والصور من Pinterest بدقة عالية.',
      en: 'Save video pins and high-resolution images from Pinterest easily.',
      fr: 'Enregistrez facilement les vidéos et images de Pinterest en haute résolution.',
      es: 'Guarda pines de video e imágenes de alta resolución de Pinterest fácilmente.',
      de: 'Speichern Sie Video-Pins und hochauflösende Bilder von Pinterest einfach.',
      it: 'Salva facilmente video pin e immagini ad alta risoluzione da Pinterest.',
    },
    description: {
      ar: 'حفظ دبابيس الفيديو من بينتريست مباشرة.',
      en: 'Save video pins directly from Pinterest.',
      fr: 'Enregistrez des épingles vidéo directement depuis Pinterest.',
      es: 'Guarda pines de video directamente desde Pinterest.',
      de: 'Speichern Sie Video-Pins direkt von Pinterest.',
      it: 'Salva i video pin direttamente da Pinterest.',
    },
    features: {
      ar: ['دعم روابط pin.it المباشرة', 'حفظ الفيديوهات بجودة HD', 'تحميل الصور العالية الدقة', 'مجاني لجميع المستخدمين'],
      en: ['Short pin.it URLs Supported', 'HD Video Quality', 'High Res Photo Download', '100% Free'],
      fr: ['URL courtes pin.it supportées', 'Qualité vidéo HD', 'Téléchargement photo haute res', '100% Gratuit'],
      es: ['Soporta enlaces cortos pin.it', 'Calidad de video HD', 'Fotos de alta resolución', '100% Gratis'],
      de: ['Kurze pin.it URLs unterstützt', 'HD Videoqualität', 'Hochauflösendes Foto', '100% Kostenlos'],
      it: ['Supporta URL brevi pin.it', 'Qualità video HD', 'Foto ad alta risoluzione', '100% Gratuito'],
    },
  },
  reddit: {
    slug: 'reddit',
    name: 'Reddit',
    iconName: 'MessageSquare',
    color: 'from-orange-600 to-amber-600',
    badgeBg: 'bg-orange-500/10 border-orange-500/30',
    badgeText: 'text-orange-400',
    placeholderUrl: 'https://www.reddit.com/r/videos/comments/123456/',
    popular: false,
    seoKeywords: ['reddit video downloader', 'download reddit video with audio', 'redditsave'],
    supportedFormats: ['MP4 HD Video with Audio', 'Audio MP3'],
    titleTemplate: {
      ar: 'تحميل فيديوهات ريديت مع الصوت (Reddit Video Downloader)',
      en: 'Reddit Video Downloader with Audio (HD MP4)',
      fr: 'Téléchargeur de Vidéos Reddit avec Audio',
      es: 'Descargador de Videos de Reddit con Audio',
      de: 'Reddit Video Downloader mit Audio',
      it: 'Downloader Video Reddit con Audio',
    },
    subtitle: {
      ar: 'احفظ فيديوهات منشورات ريديت مع دمج الصوت والصورة تلقائيًا بأعلى دقة.',
      en: 'Save Reddit videos with merged audio and video tracks automatically in high resolution.',
      fr: 'Enregistrez des vidéos Reddit avec pistes audio et vidéo fusionnées automatiquement.',
      es: 'Guarda videos de Reddit con pistas de audio y video fusionadas automáticamente.',
      de: 'Speichern Sie Reddit-Videos mit automatisch zusammengefügtem Ton und Bild.',
      it: 'Salva i video di Reddit con tracce audio e video unite automaticamente.',
    },
    description: {
      ar: 'دمج وتنزيل فيديوهات ريديت بالصوت.',
      en: 'Automatic audio/video merger for Reddit downloads.',
      fr: 'Fusion automatique audio/vidéo pour les téléchargements Reddit.',
      es: 'Fusión automática de audio y video para descargas de Reddit.',
      de: 'Zusammenfügung von Audio und Video für Reddit Downloads.',
      it: 'Unione automatica di audio e video per i download da Reddit.',
    },
    features: {
      ar: ['دمج الصوت مع الفيديو تلقائيًا', 'جودة HD 1080p', 'تحويل المقطع لصوت MP3', 'سرعة عالية'],
      en: ['Automatic Audio + Video Merge', 'HD 1080p Quality', 'Extract MP3 Track', 'Lightning Fast'],
      fr: ['Fusion automatique audio + vidéo', 'Qualité HD 1080p', 'Extraire la piste MP3', 'Très rapide'],
      es: ['Fusión automática audio + video', 'Calidad HD 1080p', 'Extraer pista MP3', 'Ultrarrápido'],
      de: ['Automatische Audio + Video Fusion', 'HD 1080p Qualität', 'MP3 Tonspur', 'Blitzschnell'],
      it: ['Unione automatica audio + video', 'Qualità HD 1080p', 'Estrarre traccia MP3', 'Velocissimo'],
    },
  },
  threads: {
    slug: 'threads',
    name: 'Threads',
    iconName: 'AtSign',
    color: 'from-zinc-700 to-black',
    badgeBg: 'bg-zinc-500/10 border-zinc-500/30',
    badgeText: 'text-zinc-300',
    placeholderUrl: 'https://www.threads.net/@user/post/123456789',
    popular: false,
    seoKeywords: ['threads video downloader', 'download threads video', 'save threads video'],
    supportedFormats: ['MP4 HD Video', 'JPEG Image'],
    titleTemplate: {
      ar: 'تحميل فيديوهات ثريدز (Threads Video Downloader)',
      en: 'Threads Video & Image Downloader (HD MP4)',
      fr: 'Téléchargeur de Vidéos Threads',
      es: 'Descargador de Videos de Threads',
      de: 'Threads Video Downloader',
      it: 'Downloader Video Threads',
    },
    subtitle: {
      ar: 'احفظ الفيديوهات والصور من منصة ثريدز Threads التابعة لإنستغرام.',
      en: 'Save videos and photos from Meta Threads app directly to your phone or desktop.',
      fr: 'Enregistrez des vidéos et des photos depuis l\'application Threads directement.',
      es: 'Guarda videos y fotos de la aplicación Threads directamente en tu dispositivo.',
      de: 'Speichern Sie Videos und Fotos von Meta Threads direkt auf Ihrem Gerät.',
      it: 'Salva video e foto dall\'app Threads direttamente sul tuo dispositivo.',
    },
    description: {
      ar: 'تنزيل وسائط منصة ثريدز بسهولة.',
      en: 'Download videos and media from Threads easily.',
      fr: 'Téléchargez facilement les médias de Threads.',
      es: 'Descarga archivos multimedia de Threads fácilmente.',
      de: 'Download von Threads Medien leicht gemacht.',
      it: 'Scarica facilmente i media da Threads.',
    },
    features: {
      ar: ['دعم فيديوهات وصور ثريدز', 'جودة أصيلة ممتازة', 'بدون إعلانات مزعجة', 'مجاني بالكامل'],
      en: ['Threads Videos & Photos', 'Original Quality', 'No Annoying Popups', '100% Free'],
      fr: ['Vidéos et Photos Threads', 'Qualité originale', 'Pas de popups', '100% Gratuit'],
      es: ['Videos y Fotos de Threads', 'Calidad original', 'Sin popups molestos', '100% Gratis'],
      de: ['Threads Videos & Fotos', 'Originalqualität', 'Keine Popups', '100% Kostenlos'],
      it: ['Video e Foto Threads', 'Qualità originale', 'Nessun popup', '100% Gratuito'],
    },
  },
  linkedin: {
    slug: 'linkedin',
    name: 'LinkedIn',
    iconName: 'Linkedin',
    color: 'from-blue-700 to-indigo-800',
    badgeBg: 'bg-blue-600/10 border-blue-600/30',
    badgeText: 'text-blue-300',
    placeholderUrl: 'https://www.linkedin.com/posts/user_activity-123456789',
    popular: false,
    seoKeywords: ['linkedin video downloader', 'download linkedin video hd', 'save linkedin video'],
    supportedFormats: ['MP4 HD Video', 'MP3 Audio'],
    titleTemplate: {
      ar: 'تحميل فيديوهات لينكد إن (LinkedIn Video Downloader)',
      en: 'LinkedIn Video Downloader (HD MP4)',
      fr: 'Téléchargeur de Vidéos LinkedIn',
      es: 'Descargador de Videos de LinkedIn',
      de: 'LinkedIn Video Downloader',
      it: 'Downloader Video LinkedIn',
    },
    subtitle: {
      ar: 'احفظ الفيديوهات الاحترافية والمقاطع التعليمية من منشورات LinkedIn بدقة جيدة.',
      en: 'Download professional videos and educational posts from LinkedIn easily.',
      fr: 'Téléchargez des vidéos professionnelles depuis LinkedIn facilement.',
      es: 'Descarga videos profesionales y publicaciones de LinkedIn fácilmente.',
      de: 'Laden Sie professionelle Videos von LinkedIn einfach herunter.',
      it: 'Scarica facilmente video professionali da LinkedIn.',
    },
    description: {
      ar: 'تنزيل فيديوهات لينكد إن بجودة عالية.',
      en: 'Save LinkedIn video posts directly.',
      fr: 'Enregistrez les vidéos LinkedIn directement.',
      es: 'Guarda publicaciones de video de LinkedIn directamente.',
      de: 'LinkedIn Video-Beiträge direkt speichern.',
      it: 'Salva i post video di LinkedIn direttamente.',
    },
    features: {
      ar: ['دعم المنشورات والفيديوهات', 'دقة HD واضحة', 'استخراج الصوت MP3', 'سرعة تحميل فائقة'],
      en: ['Supports Posts & Videos', 'Clear HD Resolution', 'MP3 Audio Extraction', 'Fast Download Speed'],
      fr: ['Supporte posts et vidéos', 'Résolution HD nette', 'Extraction MP3', 'Téléchargement rapide'],
      es: ['Soporta publicaciones y videos', 'Resolución HD nítida', 'Extracción de MP3', 'Rápida velocidad'],
      de: ['Unterstützt Beiträge & Videos', 'Scharfe HD Auflösung', 'MP3 Tonextraktion', 'Schneller Download'],
      it: ['Supporta post e video', 'Risoluzione HD nitida', 'Estrazione audio MP3', 'Download veloce'],
    },
  },
};

export const DEFAULT_FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    platform: 'general',
    order: 1,
    question: {
      ar: 'هل أداة OmniFetch Pro مجانية بالكامل؟',
      en: 'Is OmniFetch Pro completely free to use?',
      fr: 'OmniFetch Pro est-il totalement gratuit ?',
      es: '¿OmniFetch Pro es completamente gratuito?',
      de: 'Ist OmniFetch Pro vollkommen kostenlos?',
      it: 'OmniFetch Pro è completamente gratuito?',
    },
    answer: {
      ar: 'نعم، الخدمة مجانية 100% وبدون أي رسوم خفية، كما أنها لا تتطلب إنشاء حساب أو تسجيل دخول.',
      en: 'Yes, 100% free with no hidden subscriptions, limits, or mandatory registration required.',
      fr: 'Oui, 100% gratuit sans inscription ni abonnement requis.',
      es: 'Sí, es 100% gratuito sin suscripciones ni necesidad de registrarse.',
      de: 'Ja, 100% kostenlos ohne versteckte Gebühren oder Registrierung.',
      it: 'Sì, è gratuito al 100% senza registrazioni o costi nascosti.',
    },
  },
  {
    id: 'faq-2',
    platform: 'general',
    order: 2,
    question: {
      ar: 'كيف أستطيع إزالة العلامة المائية من فيديوهات تيك توك؟',
      en: 'How do I download TikTok videos without watermark?',
      fr: 'Comment télécharger des vidéos TikTok sans filigrane ?',
      es: '¿Cómo descargar videos de TikTok sin marca de agua?',
      de: 'Wie lade ich TikTok-Videos ohne Wasserzeichen herunter?',
      it: 'Come scaricare video TikTok senza filigrana?',
    },
    answer: {
      ar: 'قم بنسخ رابط فيديو TikTok واكليكه في مربع البحث هنا، وسيقوم النظام تلقائيًا بإزالة الشعار وتوفير خيار "No Watermark MP4".',
      en: 'Simply copy the TikTok video URL, paste it into our search bar, and click Download. Our system automatically scrubs the watermark.',
      fr: 'Collez simplement le lien de la vidéo TikTok dans notre barre de recherche. Notre système supprime automatiquement le filigrane.',
      es: 'Solo copia el enlace del video de TikTok, pégalo en la barra de búsqueda y haz clic en Descargar.',
      de: 'Fügen Sie einfach den TikTok-Link in das Suchfeld ein. Das Wasserzeichen wird automatisch entfernt.',
      it: 'Incolla il link del video TikTok nella barra di ricerca. Il sistema rimuoverà automaticamente la filigrana.',
    },
  },
  {
    id: 'faq-3',
    platform: 'general',
    order: 3,
    question: {
      ar: 'هل يمكنني التحميل على أجهزة الآيفون (iOS) والأندرويد؟',
      en: 'Can I download videos on iPhone (iOS) and Android devices?',
      fr: 'Puis-je télécharger des vidéos sur iPhone (iOS) et Android ?',
      es: '¿Puedo descargar videos en dispositivos iPhone (iOS) y Android?',
      de: 'Kann ich Videos auf iPhone (iOS) und Android herunterladen?',
      it: 'Posso scaricare video su dispositivi iPhone (iOS) e Android?',
    },
    answer: {
      ar: 'بالتأكيد! يعمل الموقع بسلاسة على كافة المتصفحات كـ Safari و Chrome و Firefox على كافة الأجهزة الذكية والأجهزة المحمولة.',
      en: 'Absolutely! OmniFetch Pro works smoothly on Safari, Chrome, Edge, and Firefox across iPhone, iPad, Android, Mac, and Windows.',
      fr: 'Absolument ! OmniFetch Pro fonctionne parfaitement sur Safari, Chrome et Firefox sur iOS et Android.',
      es: '¡Absolutamente! Funciona en Safari, Chrome y Firefox en todos los dispositivos móviles y computadoras.',
      de: 'Ja! OmniFetch Pro funktioniert einwandfrei auf allen gängigen Browsern und Geräten.',
      it: 'Assolutamente sì! OmniFetch Pro funziona perfettamente su Safari, Chrome e Firefox.',
    },
  },
  {
    id: 'faq-4',
    platform: 'general',
    order: 4,
    question: {
      ar: 'أين يتم حفظ الملفات بعد التحميل؟',
      en: 'Where are downloaded files saved on my device?',
      fr: 'Où sont enregistrés les fichiers téléchargés ?',
      es: '¿Dónde se guardan los archivos descargados?',
      de: 'Wo werden die heruntergeladenen Dateien gespeichert?',
      it: 'Dove vengono salvati i file scaricati?',
    },
    answer: {
      ar: 'تُحفظ جميع المقاطع التي تقوم بتحميلها في مجلد "Downloads" (التحميلات) الافتراضي في جهازك أو استوديو الهاتف.',
      en: 'All downloaded videos and audio files are automatically saved in your default "Downloads" folder or mobile Photos app.',
      fr: 'Tous les fichiers téléchargés sont automatiquement enregistrés dans votre dossier "Téléchargements" par défaut.',
      es: 'Todos los archivos descargados se guardan automáticamente en tu carpeta predeterminada de "Descargas".',
      de: 'Alle Dateien werden automatisch in Ihrem Standard-Download-Ordner gespeichert.',
      it: 'Tutti i file scaricati vengono salvati automaticamente nella cartella "Download" predefinita.',
    },
  },
];

export const INITIAL_BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    slug: 'how-to-download-tiktok-videos-without-watermark-2026',
    category: 'tutorials',
    author: 'OmniFetch Tech Team',
    publishedAt: '2026-07-20',
    readTimeMinutes: 4,
    views: 3420,
    coverImage: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80',
    tags: ['TikTok', 'No Watermark', 'Tutorial', 'HD Video'],
    title: {
      ar: 'كيفية تحميل فيديوهات تيك توك بدون علامة مائية في 2026 بجودة عالية',
      en: 'How to Download TikTok Videos Without Watermark in 2026 (Ultra HD Guide)',
      fr: 'Comment télécharger des vidéos TikTok sans filigrane en 2026 (Guide HD)',
      es: 'Cómo descargar videos de TikTok sin marca de agua en 2026 (Guía HD)',
      de: 'So laden Sie TikTok-Videos ohne Wasserzeichen im Jahr 2026 herunter',
      it: 'Come scaricare video TikTok senza filigrana nel 2026 (Guida HD)',
    },
    excerpt: {
      ar: 'شرح تفصيلي بالخطوات حول إزالة شعار تيك توك وتنزيل المقاطع بدقة 1080p وتحويلها إلى MP3 بسهولة.',
      en: 'Step-by-step guide to removing the TikTok logo, downloading 1080p video clips, and extracting crystal clear MP3 audio tracks.',
      fr: 'Guide étape par étape pour supprimer le logo TikTok et télécharger des vidéos 1080p.',
      es: 'Guía paso a paso para eliminar el logotipo de TikTok y descargar videos en 1080p.',
      de: 'Schritt-für-Schritt-Anleitung zur Entfernung des TikTok-Logos und zum Download in 1080p.',
      it: 'Guida passo-passo per rimuovere il logo TikTok e scaricare video in 1080p.',
    },
    content: {
      ar: `
### لماذا يفضل العديد إزالة العلامة المائية من تيك توك؟

عند مشاركة مقاطع تيك توك على منصات أخرى كـ Instagram Reels أو YouTube Shorts، قد تنخفض نسب المشاهدة بسبب خوارزميات الترويج إذا كان الشعار ظاهراً. يتيح لك موقع **OmniFetch Pro** الحصول على النسخة الأصلية النقية بنقرة زر واحدة.

#### الخطوات البسيطة:
1. افتح تطبيق TikTok وحدد الفيديو المطلوب.
2. اضغط على زر "مشاركة" (Share) ثم اختر "نسخ الرابط" (Copy Link).
3. توجه إلى موقع **OmniFetch Pro** في متصفحك.
4. الصق الرابط واضغط على **Download** للحصول على ملف MP4 الصافي بدون شعار.
      `,
      en: `
### Why Remove the TikTok Watermark?

When re-sharing short-form video content onto Instagram Reels, Facebook Reels, or YouTube Shorts, platform algorithms often lower the distribution reach of videos displaying competitive logos. **OmniFetch Pro** enables content creators and users to save pristine HD originals.

#### Step-by-Step Instructions:
1. Open the TikTok app and locate your favorite clip.
2. Tap the **Share** icon and select **Copy Link**.
3. Launch **OmniFetch Pro** on any mobile or desktop web browser.
4. Paste the URL into the input field and hit **Download** to obtain the 1080p clean MP4 file.
      `,
      fr: `
### Pourquoi supprimer le filigrane TikTok ?

Lors du partage de vidéos TikTok sur d'autres réseaux, les algorithmes peuvent réduire la visibilité des contenus affichant des logos concurrents. **OmniFetch Pro** vous permet d'obtenir des originaux HD impeccables.
      `,
      es: `
### ¿Por qué eliminar la marca de agua de TikTok?

Al compartir videos de TikTok en otras plataformas, los algoritmos suelen reducir el alcance si detectan logotipos. **OmniFetch Pro** te ayuda a guardar el video original en HD.
      `,
      de: `
### Warum das TikTok-Wasserzeichen entfernen?

Beim Teilen von TikTok-Videos auf anderen Plattformen begrenzen Algorithmen oft die Reichweite. **OmniFetch Pro** bietet saubere HD-Downloads.
      `,
      it: `
### Perché rimuovere la filigrana di TikTok?

Quando condividi video TikTok su altre piattaforme, gli algoritmi possono ridurre la copertura. **OmniFetch Pro** ti permette di salvare file HD puliti.
      `,
    },
  },
  {
    id: 'blog-2',
    slug: 'best-free-youtube-shorts-and-4k-video-downloaders',
    category: 'platform-news',
    author: 'OmniFetch Tech Team',
    publishedAt: '2026-07-15',
    readTimeMinutes: 5,
    views: 2890,
    coverImage: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=800&q=80',
    tags: ['YouTube', 'Shorts', '4K Video', 'Audio MP3'],
    title: {
      ar: 'أفضل الطرق لتحميل شورتس وفيديوهات يوتيوب 4K بصيغة MP3 و MP4',
      en: 'Top Methods to Download YouTube Shorts & 4K Videos in MP3 / MP4 in 2026',
      fr: 'Meilleures méthodes pour télécharger des vidéos YouTube Shorts et 4K',
      es: 'Las mejores formas de descargar YouTube Shorts y videos 4K en 2026',
      de: 'Beste Methoden zum Herunterladen von YouTube Shorts & 4K Videos',
      it: 'I migliori metodi per scaricare YouTube Shorts e video 4K',
    },
    excerpt: {
      ar: 'استعراض شامل لأدق أدوات التحميل المجانية دون الحاجة لتثبيت برامج ثقيلة على جهازك.',
      en: 'Comprehensive overview of web-based tools that allow seamless 4K video downloads and 320kbps MP3 audio conversions.',
      fr: 'Aperçu complet des outils en ligne permettant de télécharger des vidéos 4K et des fichiers MP3 320kbps.',
      es: 'Revisión completa de herramientas en línea para descargar videos en 4K y audio MP3 de 320kbps.',
      de: 'Umfassender Überblick über Online-Tools für 4K-Downloads und 320kbps MP3-Konvertierungen.',
      it: 'Panoramica completa degli strumenti online per scaricare video 4K e audio MP3 a 320kbps.',
    },
    content: {
      ar: `
### القوة في تحميل فيديوهات YouTube مع OmniFetch Pro

تطورت جودة العرض على يوتيوب لتصل إلى دقة 4K و 8K. يوفر موقعنا معالجة سريعة لسحب ملفات MP4 و MP3 بدون التأثير على سلاسة الصورة ونقاء الصوت.
      `,
      en: `
### Leveraging OmniFetch Pro for High-Resolution YouTube Downloads

YouTube videos offer incredible 4K HDR quality. **OmniFetch Pro** extracts streams directly into user-friendly MP4 files without quality loss.
      `,
      fr: `
### Téléchargez des vidéos YouTube en haute résolution avec OmniFetch Pro.
      `,
      es: `
### Descarga videos de YouTube en alta resolución con OmniFetch Pro.
      `,
      de: `
### Nutzen Sie OmniFetch Pro für hochauflösende YouTube-Downloads.
      `,
      it: `
### Scarica video YouTube ad alta risoluzione con OmniFetch Pro.
      `,
    },
  },
];

export const DEFAULT_ADS_CONFIG: AdPlacementConfig[] = [
  {
    id: 'ad-header',
    slot: 'header_banner',
    name: 'Header Top Leaderboard (728x90 / Responsive)',
    enabled: true,
    code: '<div class="text-center font-mono text-xs text-slate-400 py-2 bg-slate-800/40 rounded-lg border border-dashed border-slate-700">Google AdSense Header Banner (Responsive)</div>',
    heightPx: 90,
  },
  {
    id: 'ad-preresult',
    slot: 'pre_result',
    name: 'Pre-Result Banner (Native Ad)',
    enabled: true,
    code: '<div class="text-center font-mono text-xs text-emerald-400 py-3 bg-emerald-950/20 rounded-lg border border-dashed border-emerald-800/50">Google AdSense Pre-Download Native Display</div>',
    heightPx: 100,
  },
  {
    id: 'ad-postresult',
    slot: 'post_result',
    name: 'Post-Result Medium Rectangle (300x250 / Auto)',
    enabled: true,
    code: '<div class="text-center font-mono text-xs text-sky-400 py-4 bg-sky-950/20 rounded-lg border border-dashed border-sky-800/50">Google AdSense Post-Download Banner</div>',
    heightPx: 120,
  },
  {
    id: 'ad-sidebar',
    slot: 'sidebar',
    name: 'Sidebar Ad Banner',
    enabled: true,
    code: '<div class="text-center font-mono text-xs text-amber-400 py-8 bg-amber-950/20 rounded-lg border border-dashed border-amber-800/50">Google AdSense Sidebar Box</div>',
    heightPx: 250,
  },
  {
    id: 'ad-footer',
    slot: 'footer_banner',
    name: 'Footer Sticky Banner',
    enabled: true,
    code: '<div class="text-center font-mono text-xs text-purple-400 py-2 bg-purple-950/20 rounded-lg border border-dashed border-purple-800/50">Google AdSense Footer Leaderboard</div>',
    heightPx: 90,
  },
];
