import { useState, useEffect } from 'react';
import {
  Database,
  Server,
  Key,
  User,
  CheckCircle2,
  AlertTriangle,
  RefreshCw,
  X,
  HardDrive,
  Copy,
  Check,
  Globe,
  Lock,
  ArrowLeftRight,
  Download,
  Sparkles,
} from 'lucide-react';
import {
  HostingerDbConfig,
  getLocalHostingerConfig,
  installHostingerDb,
  checkHostingerDbStatus,
} from '../lib/hostingerDb';

interface HostingerDbInstallerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function HostingerDbInstallerModal({ isOpen, onClose }: HostingerDbInstallerModalProps) {
  const [config, setConfig] = useState<HostingerDbConfig>({
    db_host: 'localhost',
    db_port: '3306',
    db_name: '',
    db_user: '',
    db_pass: '',
  });

  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [statusMessage, setStatusMessage] = useState<{ type: 'success' | 'error' | 'info'; text: string } | null>(null);
  const [isConnected, setIsConnected] = useState(false);
  const [connectedDbName, setConnectedDbName] = useState('');
  const [copiedScript, setCopiedScript] = useState(false);

  useEffect(() => {
    if (isOpen) {
      const local = getLocalHostingerConfig();
      setConfig((prev) => ({
        ...prev,
        db_host: local.db_host || 'localhost',
        db_port: local.db_port || '3306',
        db_name: local.db_name || '',
        db_user: local.db_user || '',
        db_pass: local.db_pass || '',
      }));

      checkHostingerDbStatus().then((st) => {
        if (st.installed && st.db_name) {
          setIsConnected(true);
          setConnectedDbName(st.db_name);
        }
      });
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleInputChange = (field: keyof HostingerDbConfig, value: string) => {
    setConfig((prev) => ({ ...prev, [field]: value }));
  };

  const handleTestAndInstall = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!config.db_name.trim() || !config.db_user.trim()) {
      setStatusMessage({
        type: 'error',
        text: 'يرجى إدخال اسم قاعدة البيانات واسم المستخدم الخاصين بـ Hostinger!',
      });
      return;
    }

    setLoading(true);
    setStatusMessage({
      type: 'info',
      text: 'جاري اختبار الاتصال بسيرفر هوستنجر وتثبيت جداول SQL تلقائياً...',
    });

    const result = await installHostingerDb(config);

    setLoading(false);
    if (result.success) {
      setIsConnected(true);
      setConnectedDbName(config.db_name);
      setStatusMessage({
        type: 'success',
        text: result.message || 'تم ربط الموقع بنجاح بقاعدة بيانات Hostinger MySQL!',
      });
    } else {
      setStatusMessage({
        type: 'error',
        text: result.error || 'فشل الاتصال بقاعدة بيانات Hostinger. يرجى التحقق من صحة اسم المستخدم وكلمة المرور.',
      });
    }
  };

  const generatePhpConfigFile = () => {
    const content = `<?php
// Hostinger MySQL Database Configuration
// Generated by OmniFetch Web Installer

$db_host = "${config.db_host || 'localhost'}";
$db_port = "${config.db_port || '3306'}";
$db_name = "${config.db_name}";
$db_user = "${config.db_user}";
$db_pass = "${config.db_pass}";

try {
    $pdo = new PDO("mysql:host=$db_host;port=$db_port;dbname=$db_name;charset=utf8mb4", $db_user, $db_pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
    ]);
} catch (PDOException $e) {
    die("Database Connection Failed: " . $e->getMessage());
}
`;
    navigator.clipboard.writeText(content);
    setCopiedScript(true);
    setTimeout(() => setCopiedScript(false), 3000);
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6 bg-slate-950/80 backdrop-blur-xl animate-fade-in dir-rtl overflow-y-auto">
      <div className="relative w-full max-w-2xl my-auto rounded-3xl bg-slate-900 border border-slate-800 shadow-2xl shadow-indigo-950/50 overflow-hidden text-right">
        {/* Top Header Banner */}
        <div className="relative px-6 py-5 bg-gradient-to-r from-indigo-900 via-slate-900 to-purple-900 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-indigo-600/30 border border-indigo-500/40 flex items-center justify-center text-indigo-400 shadow-lg">
              <Database className="w-6 h-6 animate-pulse" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg font-black text-white">إعداد قاعدة بيانات Hostinger MySQL</h3>
                <span className="text-[10px] px-2 py-0.5 rounded-full font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30">
                  Web Installer PRO
                </span>
              </div>
              <p className="text-xs text-slate-300 mt-0.5">
                ربط مباشر بدون أي خدمات خارجية اعتماداً على سيرفر هوستنجر الخاص بك
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Status Indicator Bar */}
        {isConnected && (
          <div className="px-6 py-3 bg-emerald-950/60 border-b border-emerald-800/50 flex items-center justify-between">
            <div className="flex items-center gap-2 text-xs font-bold text-emerald-300">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>الموقع متصل الآن بقاعدة بيانات هوستنجر: <strong className="font-mono text-emerald-200">{connectedDbName}</strong></span>
            </div>
            <span className="text-[10px] px-2 py-0.5 rounded font-extrabold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
              نشط ومهيأ
            </span>
          </div>
        )}

        {/* Content Body */}
        <div className="p-6 space-y-6">
          {/* Instruction Alert */}
          <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 text-xs text-slate-300 leading-relaxed flex gap-3">
            <Server className="w-5 h-5 text-indigo-400 shrink-0 mt-0.5" />
            <div>
              <strong className="text-white block mb-1">كيفية الحصول على بيانات الاتصال من Hostinger hPanel:</strong>
              1. افتح لوحة تحكم هوستنجر <strong>hPanel</strong> واذهب إلى قسم <strong>Databases (قواعد البيانات)</strong>.<br />
              2. قم بإنشاء قاعدة بيانات جديدة وشخص اسم المستخدم وكلمة المرور.<br />
              3. اكتب اسم قاعدة البيانات واسم المستخدم أدناه واضغط <strong>"اختبار وتثبيت القاعدة"</strong>.
            </div>
          </div>

          {/* Form */}
          <form onSubmit={handleTestAndInstall} className="space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Hostname */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                  <Globe className="w-3.5 h-3.5 text-indigo-400" />
                  <span>مضيف قاعدة البيانات (Host)</span>
                </label>
                <input
                  type="text"
                  value={config.db_host}
                  onChange={(e) => handleInputChange('db_host', e.target.value)}
                  placeholder="localhost"
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm font-mono text-white focus:outline-none focus:border-indigo-500 transition-all"
                />
                <span className="text-[10px] text-slate-400 mt-1 block">اتركه <code className="text-indigo-300">localhost</code> لمعظم استضافات هوستنجر</span>
              </div>

              {/* Port */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                  <ArrowLeftRight className="w-3.5 h-3.5 text-purple-400" />
                  <span>منفذ MySQL (Port)</span>
                </label>
                <input
                  type="text"
                  value={config.db_port}
                  onChange={(e) => handleInputChange('db_port', e.target.value)}
                  placeholder="3306"
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm font-mono text-white focus:outline-none focus:border-indigo-500 transition-all"
                />
              </div>

              {/* Database Name */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                  <HardDrive className="w-3.5 h-3.5 text-emerald-400" />
                  <span>اسم قاعدة البيانات (Database Name) *</span>
                </label>
                <input
                  type="text"
                  required
                  value={config.db_name}
                  onChange={(e) => handleInputChange('db_name', e.target.value)}
                  placeholder="u123456789_omni_db"
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm font-mono text-white focus:outline-none focus:border-emerald-500 transition-all"
                />
              </div>

              {/* Database User */}
              <div>
                <label className="block text-xs font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                  <User className="w-3.5 h-3.5 text-amber-400" />
                  <span>اسم مستخدم القاعدة (DB Username) *</span>
                </label>
                <input
                  type="text"
                  required
                  value={config.db_user}
                  onChange={(e) => handleInputChange('db_user', e.target.value)}
                  placeholder="u123456789_user"
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm font-mono text-white focus:outline-none focus:border-amber-500 transition-all"
                />
              </div>
            </div>

            {/* Database Password */}
            <div>
              <label className="block text-xs font-bold text-slate-300 mb-1.5 flex items-center gap-1.5">
                <Lock className="w-3.5 h-3.5 text-rose-400" />
                <span>كلمة مرور قاعدة البيانات (Password)</span>
              </label>
              <div className="relative">
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={config.db_pass}
                  onChange={(e) => handleInputChange('db_pass', e.target.value)}
                  placeholder="••••••••••••"
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-sm font-mono text-white focus:outline-none focus:border-rose-500 transition-all"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-xs font-bold text-slate-400 hover:text-white"
                >
                  {showPassword ? 'إخفاء' : 'إظهار'}
                </button>
              </div>
            </div>

            {/* Status Message Box */}
            {statusMessage && (
              <div
                className={`p-3.5 rounded-2xl text-xs font-semibold flex items-center gap-2.5 ${
                  statusMessage.type === 'success'
                    ? 'bg-emerald-950/80 border border-emerald-500/50 text-emerald-200'
                    : statusMessage.type === 'error'
                    ? 'bg-rose-950/80 border border-rose-500/50 text-rose-200'
                    : 'bg-indigo-950/80 border border-indigo-500/50 text-indigo-200'
                }`}
              >
                {statusMessage.type === 'success' && <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />}
                {statusMessage.type === 'error' && <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0" />}
                {statusMessage.type === 'info' && <RefreshCw className="w-4 h-4 text-indigo-400 animate-spin shrink-0" />}
                <span>{statusMessage.text}</span>
              </div>
            )}

            {/* Buttons */}
            <div className="flex flex-col sm:flex-row items-center gap-3 pt-2">
              <button
                type="submit"
                disabled={loading}
                className="w-full sm:flex-1 py-3 px-5 rounded-2xl bg-gradient-to-r from-indigo-600 via-purple-600 to-pink-600 hover:from-indigo-500 hover:to-pink-500 text-white font-black text-xs sm:text-sm flex items-center justify-center gap-2 shadow-xl shadow-indigo-600/30 transition-all active:scale-95 disabled:opacity-50"
              >
                {loading ? (
                  <>
                    <RefreshCw className="w-4 h-4 animate-spin" />
                    <span>جاري التثبيت والاختبار...</span>
                  </>
                ) : (
                  <>
                    <Sparkles className="w-4 h-4 text-amber-300 animate-bounce" />
                    <span>اختبار الاتصال وتثبيت قاعدة البيانات الآن</span>
                  </>
                )}
              </button>

              <button
                type="button"
                onClick={generatePhpConfigFile}
                className="w-full sm:w-auto py-3 px-4 rounded-2xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold text-xs flex items-center justify-center gap-2 border border-slate-700 transition-all"
                title="نسخ كود ملف db_config.php تلقائياً"
              >
                {copiedScript ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4 text-indigo-400" />}
                <span>{copiedScript ? 'تم النسخ!' : 'نسخ ملف config.php'}</span>
              </button>
            </div>
          </form>

          {/* Installed Tables Summary */}
          <div className="pt-4 border-t border-slate-800">
            <h4 className="text-xs font-bold text-slate-300 mb-2 flex items-center gap-1.5">
              <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
              <span>الجداول التي يتم إنشاؤها تلقائياً على Hostinger:</span>
            </h4>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px] font-mono text-slate-400">
              <div className="p-2 rounded-xl bg-slate-950 border border-slate-800">✓ trending_downloads</div>
              <div className="p-2 rounded-xl bg-slate-950 border border-slate-800">✓ site_settings</div>
              <div className="p-2 rounded-xl bg-slate-950 border border-slate-800">✓ download_logs</div>
              <div className="p-2 rounded-xl bg-slate-950 border border-slate-800">✓ visitor_stats</div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
          <span>متوافق 100% مع استضافة Hostinger المشتركة</span>
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 font-bold transition-all"
          >
            إغلاق
          </button>
        </div>
      </div>
    </div>
  );
}
